### ISSUE TITLE
Release 1.0?

### ISSUE THREAD

**Issue by no-reply** [samvera/iiif_manifest#38]
This seems pretty stable, and releasing 1.0 will make managing it as a dependency (e.g. in Hyrax) easier. 

See: https://github.com/samvera/hyrax/pull/3880

**Comment by cjcolvar** [comment]
There was also discussion before about promoting it to core.  It looks like Hyrax, Avalon, Figgy, Spotlight, and others depend on it.

**Comment by mark-dce** [comment]
Done - see https://rubygems.org/gems/iiif_manifest
