### ISSUE TITLE
Add support for Rails 6.0.z releases

### ISSUE THREAD

**Issue by jrgriffiniii** [samvera/iiif_manifest#44]
Rails version 6.0.0 was released on 08/16/2019, and in accordance with the charter of the current phase of the Component Maintenance Working Group, the CircleCI configuration for this should be updated.

**Comment by jrgriffiniii** [comment]
This is still valid.

**Comment by dlpierce** [comment]
ActiveSupport 6 is being used in the CircleCI runs.
